### ISSUE TITLE
error runing test.py file in cpu mode. 

### ISSUE THREAD

**Issue by ajberenstein** [CyberAgentAILab/derendering-text#12]
Hi, first of all let me congratulate you for this fantastic work. 
After following the installation instructions I tried to run the usage example in cpu_mode 
`python test.py --imgfile=example/sample.jpg --use_cpu=1` 
and I get the following error: 
[E 230209 19:16:52 test:125] Unexpected error has occurred
    Traceback (most recent call last):
      File "test.py", line 123, in <module>
        main(args)
      File "test.py", line 88, in main
        test(
      File "test.py", line 53, in test
        vd, rec_img = vectorize(pil_img, inps, outs)
      File "/home/ariel/repos/derendering-text/src/modules/postprocess/vector.py", line 114, in vectorize
        tb_param, effect_param, effect_visibility = extract_rendering_params(
      File "/home/ariel/repos/derendering-text/src/modules/postprocess/manipulate.py", line 286, in extract_rendering_params
        tb_param = get_textblob_param_with_affine(
      File "/home/ariel/repos/derendering-text/src/modules/postprocess/rpe.py", line 515, in get_textblob_param_with_affine
        text_form_dto = TextFormData(
    TypeError: __init__() missing 1 required positional argument: 'text_index'

what I can see in the file dto_skia.py, is that the dataclass TextFromData requires a text_index: int value that is not set in rpe.py file.  Please, let me know if you need more info in order to reproduce this error.
Best, 
A.

**Comment by shimoda-uec** [comment]
Thank you for reporting the error.
I fixed it.

**Comment by ajberenstein** [comment]
Thanks Shimoda, It worked. 
best,
A.
