### ISSUE TITLE
name 'get_color' is not defined

### ISSUE THREAD

**Issue by LIYHUI** [CyberAgentAILab/derendering-text#6]
when I run this ` python gen.py --bgtype=color`, there is a error:
`[D 220704 06:56:21 handler:78] placement False
[D 220704 06:56:21 gen_mode:105] 10, 0, 10000
Traceback (most recent call last):
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/handler.py", line 32, in sample_and_render
    placed = self.sampler.sample(ih, dh)
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler.py", line 71, in sample
    style_data = self.style_sampler.sample(ih, dh)
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler_lib/style_sampler.py", line 30, in sample
    effect_params = self.get_style_params(
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler_lib/style_sampler.py", line 21, in get_style_params
    grad_param = skp.get_gradation_param(
  File "/home/yonghui_li/Image_generate/derendering-text/src/skia_lib/skia_paintor.py", line 85, in get_gradation_param
    color = get_color()
NameError: name 'get_color' is not defined
Traceback (most recent call last):
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/handler.py", line 32, in sample_and_render
    placed = self.sampler.sample(ih, dh)
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler.py", line 71, in sample
    style_data = self.style_sampler.sample(ih, dh)
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler_lib/style_sampler.py", line 30, in sample
    effect_params = self.get_style_params(
  File "/home/yonghui_li/Image_generate/derendering-text/src/modules/generator/src/sampler_lib/style_sampler.py", line 21, in get_style_params
    grad_param = skp.get_gradation_param(
  File "/home/yonghui_li/Image_generate/derendering-text/src/skia_lib/skia_paintor.py", line 85, in get_gradation_param
    color = get_color()
NameError: name 'get_color' is not defined
`

**Comment by LIYHUI** [comment]
@shimoda-uec can you provide this func?

**Comment by shimoda-uec** [comment]
Thank you for reporting the errors.
Now errors are fixed.

**Comment by LIYHUI** [comment]
Thanks!
